//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JagStore.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int InvoiceItemID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public System.Guid Product { get; set; }
        public int Quantity { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ProductDiscription ProductDiscription { get; set; }
    }
}
